theme: jekyll-theme-minimal
title: 公辰（Chen Gong）
description: PhD Student (2022-2027), Department of Computer Science and Engineering, Shanghai Jiao Tong University
logo: photo.jpg
show_downloads: False
